# Generated by Django 5.2.17 on 2026-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('body', models.TextField(blank=True, default='')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status_text', models.CharField(blank=True, default='', max_length=100)),
                ('response_time_ms', models.FloatField(blank=True, null=True)),
                ('response_size_kb', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
