# Generated by Django 5.2.17 on 2026-10-03 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_collection_environment_environmentvariable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedrequest',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='savedrequest',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='savedrequest',
            name='tests',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='ApiTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('assertion_type', models.CharField(max_length=50)),
                ('target_path', models.CharField(blank=True, default='', max_length=255)),
                ('operator', models.CharField(default='equals', max_length=20)),
                ('expected_value', models.TextField(blank=True, default='')),
                ('saved_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_definitions', to='client.savedrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tests', models.IntegerField(default=0)),
                ('passed_tests', models.IntegerField(default=0)),
                ('failed_tests', models.IntegerField(default=0)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='client.collection')),
                ('saved_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='client.savedrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assertion_name', models.CharField(max_length=255)),
                ('passed', models.BooleanField(default=True)),
                ('expected', models.TextField(blank=True, default='')),
                ('received', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('test_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='client.testrun')),
            ],
        ),
    ]
