# Generated by Django 5.2.17 on 2026-10-03 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_savedrequest_description_savedrequest_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('resource_type', models.CharField(blank=True, default='', max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light'), ('system', 'System')], default='dark', max_length=20)),
                ('compact_mode', models.BooleanField(default=False)),
                ('request_timeout', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='environment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requesthistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savedrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testrun',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'name'], name='client_coll_user_id_0e5f22_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', '-updated_at'], name='client_coll_user_id_f4f5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='environment',
            index=models.Index(fields=['user', 'name'], name='client_envi_user_id_7744ef_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistory',
            index=models.Index(fields=['user', '-timestamp'], name='client_requ_user_id_240bd2_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistory',
            index=models.Index(fields=['status_code'], name='client_requ_status__690f0b_idx'),
        ),
        migrations.AddIndex(
            model_name='requesthistory',
            index=models.Index(fields=['method'], name='client_requ_method_3a6eec_idx'),
        ),
        migrations.AddIndex(
            model_name='savedrequest',
            index=models.Index(fields=['user', 'collection'], name='client_save_user_id_9fd454_idx'),
        ),
        migrations.AddIndex(
            model_name='savedrequest',
            index=models.Index(fields=['user', '-updated_at'], name='client_save_user_id_c5a2a7_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='client_audi_user_id_5788af_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='client_audi_action_229db5_idx'),
        ),
    ]
