# Generated by Django 5.2.17 on 2026-10-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_webhook_environmentvariable_is_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiversion',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedrequest',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
